services:
  mysql-db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: database
      MYSQL_USER: kaki
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-web:
    image: guswns0208/docker-study:latest
    container_name: web
    ports:
      - "80:8090"
    depends_on:
      mysql-db:
        condition: service_healthy
