name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1 # 최근 1개의 커밋을 가져온다.
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Docker Buildx # 멀티 플랫폼 빌드를 위한 설정
      uses: docker/setup-buildx-action@v3
      if: success()

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: success()
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current date # 서울 시간대의 날짜를 가져오고, 결과를 GitHub Actions 출력 변수로 저장한다.
      id: date
      if: success()
      run: |
        export TZ='Asia/Seoul' 
        echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Get git commit hash # Git의 현재 체크아웃된 커밋 해시를 짧은 형식으로 가져오고, 결과를 GitHub Actions 출력 변수로 저장한다.
      id: git
      if: success()
      run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      if: success()
      with:
        context: .
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-study:${{ steps.git.outputs.commit-hash }}
        build-args: | # steps.<step_id>.outputs.<output_key> 형식으로 이전 단계에서 GITHUB_OUTPUT 환경변수에 설정한 값을 사용한다.
          BUILD_DATE=${{ steps.date.outputs.date }}
          GIT_COMMIT_HASH=${{ steps.git.outputs.commit-hash }}
