name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: success()

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: success()
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current date
      id: date
      if: success()
      run: |
        export TZ='Asia/Seoul'
        echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Get git commit hash
      id: git
      if: success()
      run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      if: success()
      with:
        context: .
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-study:${{ steps.git.outputs.commit-hash }}
        build-args: |
          createdAt=${{ steps.date.outputs.date }}
          version=${{ steps.git.outputs.commit-hash }}
