name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      if: success()

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: success()
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current date
      id: date
      if: success()
      run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

    - name: Get git commit hash
      id: git
      if: success()
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      if: success()
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ steps.git.outputs.hash }}
        build-args: |
          BUILD_DATE=${{ steps.date.outputs.date }}
          GIT_COMMIT=${{ steps.git.outputs.hash }}
